### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by lunmx** [SAGIRI-kawaii/sagiri-bot#10]
大佬你好，我在使用过程中出现了这几个报错，该如何解决呢
``` py
[2021-02-09 16:44:54,924][ ERROR]: An open stream object is being garbage collected; call "stream.close()" explicitly.

Bot init end
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\graia\broadcast\__init__.py", line 298, in Executor
    parameter_compile_result[name] = await dii.lookup_param(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\graia\broadcast\interfaces\dispatcher.py", line 252, in lookup_param
    raise RequirementCrashed(
graia.broadcast.exceptions.RequirementCrashed: ('the dispatching requirement crashed: ', 'group', <class 'graia.application.group.Group'>, None)
```

**Comment by SAGIRI-kawaii** [comment]
这个报错我也出现过，问了Graia的作者他也不知道为什么会出现，经过观察好像并不会太多影响运行，可以尝试更新graia-mirai-application解决

**Comment by lunmx** [comment]
``` py
[2021-02-09 16:44:54,924][ ERROR]: An open stream object is being garbage collected; call "stream.close()" explicitly.
```
已更新至最新版本，这个报错依然出现，不过的确不怎么影响运行
