### ISSUE TITLE
覆盖更新后 MySQL 因缺少列报错

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#111]
手动添加 `setting.avatar_func` 后可正常启动，报错内容如下: 
```
2021-08-13 21:39:26.627 | ERROR    | SAGIRIBOT.Core.AppCore:bot_launch_init:174 - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'setting.avatar_func' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/sagiri-bot/SAGIRIBOT/Core/AppCore.py", line 150, in bot_launch_init
    await orm.insert_or_update(
  File "/root/sagiri-bot/SAGIRIBOT/ORM/AsyncORM.py", line 115, in insert_or_update
    if (await self.execute(select(table).where(*condition))).all():
  File "/root/sagiri-bot/SAGIRIBOT/ORM/AsyncORM.py", line 48, in execute
    raise e
  File "/root/sagiri-bot/SAGIRIBOT/ORM/AsyncORM.py", line 43, in execute
    result = await session.execute(sql, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 157, in execute
    return await greenlet_spawn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 120, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'setting.avatar_func' in 'field list'")
[SQL: SELECT setting.group_id, setting.group_name, setting.`repeat`, setting.frequency_limit, setting.setu, setting.`real`, setting.real_high_quality, setting.bizhi, setting.r18, setting.img_search, setting.bangumi_search, setting.compile, setting.dice, setting.avatar_func, setting.anti_revoke, setting.anti_flashimage, setting.online_notice, setting.debug, setting.switch, setting.active, setting.music, setting.r18_process, setting.speak_mode, setting.long_text_type 
FROM setting 
WHERE setting.group_id = %s]
[parameters: (167908587,)]
(Background on this error at: http://sqlalche.me/e/14/2j85)
```

**Comment by SAGIRI-kawaii** [comment]
alembic没有自动创建列嘛

**Comment by nullqwertyuiop** [comment]
没诶

**Comment by nullqwertyuiop** [comment]
上 phpMyAdmin 手动加的

**Comment by SAGIRI-kawaii** [comment]
有从启动到上述报错的log吗

**Comment by nullqwertyuiop** [comment]
他们聊天太猛了（
可能要等久一点 报错后面还有几万行

**Comment by nullqwertyuiop** [comment]
```
nohup: ignoring input
2021-08-13 21:39:20.914 | INFO     | SAGIRIBOT.Core.AppCore:__init__:50 - Initializing
2021-08-13 21:39:21.002 | INFO     | SAGIRIBOT.Core.AppCore:__init__:73 - Initialize end
2021-08-13 21:39:21.002 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.FlashImageCatcher
2021-08-13 21:39:21.012 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.FlashImageCatcher
2021-08-13 21:39:21.012 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.LeetcodeInfoHandler
2021-08-13 21:39:21.014 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LeetcodeInfoHandler
2021-08-13 21:39:21.015 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.TrendingHandlers
2021-08-13 21:39:21.166 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.TrendingHandlers
2021-08-13 21:39:21.166 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.CPGeneratorHandler
2021-08-13 21:39:21.169 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.CPGeneratorHandler
2021-08-13 21:39:21.169 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.HotWordsExplainerHandler
2021-08-13 21:39:21.171 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.HotWordsExplainerHandler
2021-08-13 21:39:21.171 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.WolframAlphaHandler
2021-08-13 21:39:21.172 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.WolframAlphaHandler
2021-08-13 21:39:21.173 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.StatusPresenterHandler
2021-08-13 21:39:21.176 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.StatusPresenterHandler
2021-08-13 21:39:21.176 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.StylePictureGeneratorHandler
2021-08-13 21:39:21.472 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.StylePictureGeneratorHandler
2021-08-13 21:39:21.472 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.PhantomTankHandler
2021-08-13 21:39:21.476 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PhantomTankHandler
2021-08-13 21:39:21.477 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.JokeHandler
2021-08-13 21:39:21.497 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.JokeHandler
2021-08-13 21:39:21.498 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.LoliconKeywordSearchHandler
2021-08-13 21:39:21.499 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LoliconKeywordSearchHandler
2021-08-13 21:39:21.500 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.MiraiEventHandler
2021-08-13 21:39:21.506 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.MiraiEventHandler
2021-08-13 21:39:21.507 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.PeroDogHandler
2021-08-13 21:39:21.508 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PeroDogHandler
2021-08-13 21:39:21.509 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.RandomWifeHandler
2021-08-13 21:39:21.511 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.RandomWifeHandler
2021-08-13 21:39:21.511 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.ImageAdderHandler
2021-08-13 21:39:21.512 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ImageAdderHandler
2021-08-13 21:39:21.513 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.TarotHandler
2021-08-13 21:39:21.515 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.TarotHandler
2021-08-13 21:39:21.515 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.GithubInfoHandler
2021-08-13 21:39:21.517 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.GithubInfoHandler
2021-08-13 21:39:21.517 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.BilibiliAppParserHandler
2021-08-13 21:39:21.519 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BilibiliAppParserHandler
2021-08-13 21:39:21.519 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.__init__
2021-08-13 21:39:21.520 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.__init__
2021-08-13 21:39:21.520 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.GroupWordCloudGeneratorHandler
2021-08-13 21:39:23.510 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.GroupWordCloudGeneratorHandler
2021-08-13 21:39:23.511 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.RepeaterHandler
2021-08-13 21:39:23.512 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.RepeaterHandler
2021-08-13 21:39:23.512 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.QrCodeGeneratorHandler
2021-08-13 21:39:23.526 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.QrCodeGeneratorHandler
2021-08-13 21:39:23.526 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.MessageMergeHandler
2021-08-13 21:39:23.528 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.MessageMergeHandler
2021-08-13 21:39:23.528 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.ImageSenderHandler
2021-08-13 21:39:23.537 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ImageSenderHandler
2021-08-13 21:39:23.537 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.JLUEpidemicReporterHandler
2021-08-13 21:39:23.622 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.ImageSearchHandler
2021-08-13 21:39:23.631 | ERROR    | SAGIRIBOT.utils:get_config:180 - getConfig Error: saucenaoCookie
2021-08-13 21:39:23.633 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ImageSearchHandler
2021-08-13 21:39:23.633 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.PoisonousChickenSoupHandler
2021-08-13 21:39:23.635 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PoisonousChickenSoupHandler
2021-08-13 21:39:23.635 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.BiliBiliBangumiScheduleHandler
2021-08-13 21:39:23.637 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BiliBiliBangumiScheduleHandler
2021-08-13 21:39:23.637 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.ChatRecorderHandler
2021-08-13 21:39:23.638 | INFO     | SAGIRIBOT.Handler.Handler:__init__:34 - Create handler -> ChatRecordHandler
2021-08-13 21:39:23.639 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ChatRecorderHandler
2021-08-13 21:39:23.640 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.AbstractMessageTransformHandler
2021-08-13 21:39:23.641 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.AbstractMessageTransformHandler
2021-08-13 21:39:23.642 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.LOLItemRaidersHandler
2021-08-13 21:39:23.643 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LOLItemRaidersHandler
2021-08-13 21:39:23.645 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.BangumiSearchHandler
2021-08-13 21:39:23.647 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BangumiSearchHandler
2021-08-13 21:39:23.648 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.PDFSearchHandler
2021-08-13 21:39:23.649 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PDFSearchHandler
2021-08-13 21:39:23.650 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.DiceHandler
2021-08-13 21:39:23.651 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.DiceHandler
2021-08-13 21:39:23.652 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.AbbreviatedPredictionHandler
2021-08-13 21:39:23.654 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.AbbreviatedPredictionHandler
2021-08-13 21:39:23.654 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.SteamGameInfoSearchHandler
2021-08-13 21:39:23.656 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.SteamGameInfoSearchHandler
2021-08-13 21:39:23.656 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.MarketingContentGeneratorHandler
2021-08-13 21:39:23.658 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.MarketingContentGeneratorHandler
2021-08-13 21:39:23.658 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.SpeakHandler
2021-08-13 21:39:23.673 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.SpeakHandler
2021-08-13 21:39:23.674 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.JLUCSWNoticeHandler
2021-08-13 21:39:23.676 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.JLUCSWNoticeHandler
2021-08-13 21:39:23.676 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.AvatarFunPicHandler
2021-08-13 21:39:24.270 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.AvatarFunPicHandler
2021-08-13 21:39:24.270 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.NetworkCompilerHandler
2021-08-13 21:39:24.272 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.NetworkCompilerHandler
2021-08-13 21:39:24.272 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.KeywordReplyHandler
2021-08-13 21:39:24.274 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.KeywordReplyHandler
2021-08-13 21:39:24.274 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.BangumiInfoSearchHandler
2021-08-13 21:39:24.275 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BangumiInfoSearchHandler
2021-08-13 21:39:24.276 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.ChatReplyHandler
2021-08-13 21:39:24.307 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ChatReplyHandler
2021-08-13 21:39:24.307 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.BotManagementHandler
2021-08-13 21:39:24.317 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BotManagementHandler
2021-08-13 21:39:24.317 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.Handler.Handlers.TodayInHistoryHandler
2021-08-13 21:39:24.318 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.TodayInHistoryHandler
2021-08-13 21:39:24.319 | DEBUG    | graia.saya:require:76 - require modules.FurAffinityImageSearchHandler
2021-08-13 21:39:24.327 | ERROR    | SAGIRIBOT.utils:get_config:180 - getConfig Error: saucenaoCookie
2021-08-13 21:39:24.328 | INFO     | graia.saya:require:95 - module loading finished: modules.FurAffinityImageSearchHandler
[2021-08-13 21:39:24,340][INFO]: initializing app...
[2021-08-13 21:39:24,394][INFO]: detecting remote's version...
2021-08-13 21:39:24.402 | INFO     | SAGIRIBOT.Core.AppCore:config_check:178 - checking config
2021-08-13 21:39:24.403 | WARNING  | SAGIRIBOT.Core.AppCore:config_check:188 - loliconApiKey无效，请检查配置！
2021-08-13 21:39:24.404 | WARNING  | SAGIRIBOT.Core.AppCore:config_check:190 - wolframAlphaKey无效，请检查配置！
2021-08-13 21:39:24.406 | INFO     | SAGIRIBOT.Core.AppCore:config_check:195 - check done
[2021-08-13 21:39:24,412][INFO]: detected remote's version: 1.10.0
[2021-08-13 21:39:24,427][INFO]: using pure websocket to receive event
[2021-08-13 21:39:24,427][INFO]: found websocket disabled, so it has been enabled.
[2021-08-13 21:39:24,553][INFO]: event receive method checked.
[2021-08-13 21:39:24,553][INFO]: this application's initialization has been completed.
[2021-08-13 21:39:24,553][INFO]: --- setting start ---
[2021-08-13 21:39:24,554][INFO]: broadcast using: <graia.broadcast.Broadcast object at 0x7ffbdb603820>
[2021-08-13 21:39:24,554][INFO]: enable log of chat: no
[2021-08-13 21:39:24,554][INFO]: debug: no
[2021-08-13 21:39:24,554][INFO]: version(remote): 1.10.0
[2021-08-13 21:39:24,554][INFO]: --- setting end ---
[2021-08-13 21:39:24,554][INFO]: application has been initialized, used 0.215s
[2021-08-13 21:39:24,554][INFO]: websocket daemon: websocket connection starting...
[2021-08-13 21:39:24,592][INFO]: websocket: connected
[2021-08-13 21:39:24,592][INFO]: websocket: ping task created
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.util.messaging] Target database is not up to date.
FAILED: Target database is not up to date.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.util.messaging] Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
FAILED: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
2021-08-13 21:39:26.627 | ERROR    | SAGIRIBOT.Core.AppCore:bot_launch_init:174 - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'setting.avatar_func' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/sagiri-bot/SAGIRIBOT/Core/AppCore.py", line 150, in bot_launch_init
    await orm.insert_or_update(
  File "/root/sagiri-bot/SAGIRIBOT/ORM/AsyncORM.py", line 115, in insert_or_update
    if (await self.execute(select(table).where(*condition))).all():
  File "/root/sagiri-bot/SAGIRIBOT/ORM/AsyncORM.py", line 48, in execute
    raise e
  File "/root/sagiri-bot/SAGIRIBOT/ORM/AsyncORM.py", line 43, in execute
    result = await session.execute(sql, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 157, in execute
    return await greenlet_spawn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 120, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'setting.avatar_func' in 'field list'")
[SQL: SELECT setting.group_id, setting.group_name, setting.`repeat`, setting.frequency_limit, setting.setu, setting.`real`, setting.real_high_quality, setting.bizhi, setting.r18, setting.img_search, setting.bangumi_search, setting.compile, setting.dice, setting.avatar_func, setting.anti_revoke, setting.anti_flashimage, setting.online_notice, setting.debug, setting.switch, setting.active, setting.music, setting.r18_process, setting.speak_mode, setting.long_text_type 
FROM setting 
WHERE setting.group_id = %s]
[parameters: (167908587,)]
(Background on this error at: http://sqlalche.me/e/14/2j85)
```

**Comment by nullqwertyuiop** [comment]
把机器人从 MySQL 换成 SQLite 就行了，很怪（

**Comment by SAGIRI-kawaii** [comment]
那确实，因为根本没测过mysql（

**Comment by nullqwertyuiop** [comment]
加黑名单也会因为缺少 global 列报错（

**Comment by nullqwertyuiop** [comment]
很怪，表 `jlu_epidemic_account_info` 反而可以成功在启动时被创建，列就不行

**Comment by SAGIRI-kawaii** [comment]
可能是mysql要写什么东西，我没用也不知道（x

**Comment by SAGIRI-kawaii** [comment]
也许这个也可以关掉（x
