### ISSUE TITLE
[Bug Report]文字转语音接口待更新

### ISSUE THREAD

**Issue by BoBppy** [SAGIRI-kawaii/sagiri-bot#112]
```
2021-08-13 23:03:41.095 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：说 bug在哪里
2021-08-13 23:03:42.441 | ERROR    | SAGIRIBOT.utils:get_config:180 - getConfig Error: txAppId
2021-08-13 23:03:42.473 | ERROR    | SAGIRIBOT.utils:get_config:180 - getConfig Error: txAppKey
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\graia\broadcast\__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "D:\Program Files\Python39\lib\site-packages\graia\broadcast\utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\Handler\Handlers\SpeakHandler.py", line 29, in speak_handler
    if result := await SpeakHandler.handle(app, message, group, member):
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\decorators.py", line 91, in wrapper
    return await func(*args, **kwargs)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\decorators.py", line 115, in wrapper
    return await func(*args, **kwargs)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\Handler\Handlers\SpeakHandler.py", line 44, in handle
    voice = await SpeakHandler.get_voice(text)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\Handler\Handlers\SpeakHandler.py", line 72, in get_voice
    sign = await get_tx_sign(params)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\utils.py", line 320, in get_tx_sign
    sign += "%s=%s&" % (i, parse.quote(params[i], safe=''))
  File "D:\Program Files\Python39\lib\urllib\parse.py", line 871, in quote
    return quote_from_bytes(string, safe)
  File "D:\Program Files\Python39\lib\urllib\parse.py", line 896, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Comment by SAGIRI-kawaii** [comment]
fixed
