### ISSUE TITLE
[Bug Report]搜番错误

### ISSUE THREAD

**Issue by BoBppy** [SAGIRI-kawaii/sagiri-bot#113]
```
2021-08-13 21:14:08.793 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：我得来排查排查错误了
2021-08-13 21:14:12.382 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：搜番
[2021-08-13 21:14:14,798][INFO]: [BOT 3312069560] Group(496476516) <- '[mirai:at:2419789089,None]请在30秒内发送要搜索的图片呐~'
2021-08-13 21:14:30.886 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <南梦芽> 的消息：[图片]
2021-08-13 21:14:39.477 | SUCCESS  | SAGIRIBOT.Handler.Handlers.BangumiSearchHandler:handle:88 - 收到用户图片，启动搜索进程！
2021-08-13 21:14:39.570 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：[图片]
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\graia\broadcast\__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "D:\Program Files\Python39\lib\site-packages\graia\broadcast\utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\Handler\Handlers\BangumiSearchHandler.py", line 35, in bangumi_search_handler
    if result := await BangumiSearchHandler.handle(app, message, group, member):
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\decorators.py", line 91, in wrapper
    return await func(*args, **kwargs)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\decorators.py", line 115, in wrapper
    return await func(*args, **kwargs)
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\Handler\Handlers\BangumiSearchHandler.py", line 92, in handle
    await BangumiSearchHandler.search_bangumi(message_received[Image][0]),
  File "D:\Program Files (x86)\mirai\sagiri-bot-2.1.6\SAGIRIBOT\Handler\Handlers\BangumiSearchHandler.py", line 107, in search_bangumi
    result = await resp.json()
  File "D:\Program Files\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://trace.moe/api/search?url=http://gchat.qpic.cn/gchatpic_new/2419789089/3986476516-2902820313-13C639EF62DF30DF8CAA7330BC952CF5/0?term=2')
2021-08-13 21:15:29.521 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：[图片]
2021-08-13 21:15:39.915 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：什么鬼
2021-08-13 21:15:43.214 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <南梦芽> 的消息：？
2021-08-13 21:15:46.977 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：我发之前就收到图片了
2021-08-13 21:15:52.861 | INFO     | __main__:group_message_handler:54 - 收到来自群 <SAGIRI-bot体验群> 中成员 <二月萧萧> 的消息：tm收成你的图片了吗
```

**Comment by SAGIRI-kawaii** [comment]
fixed
