### ISSUE TITLE
[help]运行报错

### ISSUE THREAD

**Issue by mzttsaintly** [SAGIRI-kawaii/sagiri-bot#12]
在尝试运行时发生错误：

> (botspy) Z:\boynextdoor\bin\sagiri-bot>python sagiri_bot.py
Traceback (most recent call last):
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\font_manager.py", line 1429, in <module>
    fontManager = json_load(_fmcache)
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\font_manager.py", line 1013, in json_load
    return json.load(fh, object_hook=_json_decode)
  File "c:\users\wy\appdata\local\programs\python\python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\wy\appdata\local\programs\python\python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "c:\users\wy\appdata\local\programs\python\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\wy\appdata\local\programs\python\python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 5934 column 13 (char 149822)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "sagiri_bot.py", line 31, in <module>
    from SAGIRIBOT.process.group_message_process import group_message_process
  File "Z:\boynextdoor\bin\sagiri-bot\SAGIRIBOT\process\group_message_process.py", line 44, in <module>
    from SAGIRIBOT.functions.petpet import petpet
  File "Z:\boynextdoor\bin\sagiri-bot\SAGIRIBOT\functions\petpet.py", line 3, in <module>
    from moviepy.editor import ImageSequenceClip as imageclip
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\moviepy\editor.py", line 60, in <module>
    from .video.io.sliders import sliders
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\moviepy\video\io\sliders.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\contour.py", line 16, in <module>
    import matplotlib.font_manager as font_manager
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\font_manager.py", line 1431, in <module>
    _rebuild()
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\font_manager.py", line 1425, in _rebuild
    json_dump(fontManager, _fmcache)
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\font_manager.py", line 997, in json_dump
    with cbook._lock_path(filename), open(filename, 'w') as fh:
  File "c:\users\wy\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "Z:\boynextdoor\botspy\botspy\lib\site-packages\matplotlib\cbook\__init__.py", line 1805, in _lock_path
    raise TimeoutError("""\
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    C:\Users\wy\.matplotlib\fontlist-v330.json.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.

**Comment by SAGIRI-kawaii** [comment]
> This maybe due to another process holding this lock file. If you are sure no
other Matplotlib process is running, remove this file and try again.

请按照报错提示在确认没有其他matplotlib进程运行的情况下尝试重装matplotlib

**Comment by mzttsaintly** [comment]
感谢，已正常使用。
另外发现requirements.txt中的库并不齐全，运行过程中需再装好几次其他的库
