### ISSUE TITLE
[Bug Report] 机器人运行时持续报错，但不对运行产生影响

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#125]
**环境信息**

系统版本: Debian Buster x64
源码版本: commit f18b7b2b9b2f1ae8d8a8e73feeede80e295556eb
其他信息: MySQL

**问题描述**
机器人启动后接受消息时持续报错，但不影响正常功能的使用

**日志**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 186, in Executor
    ] = await dii.lookup_param_without_log(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/interfaces/dispatcher.py", line 267, in lookup_param_without_log
    raise RequirementCrashed(
graia.broadcast.exceptions.RequirementCrashed: ('the dispatching requirement crashed: ', 'group', <class 'graia.application.group.Group'>, None)

```

**Comment by SAGIRI-kawaii** [comment]
这我也有，问了graia的作者他也不知道为啥，也不影响啥就没管（
