### ISSUE TITLE
按教程的做法无法运行

### ISSUE THREAD

**Issue by AshMOB** [SAGIRI-kawaii/sagiri-bot#13]
在跑py文件的时候报错
Traceback (most recent call last):
  File "e:/robot/sagiri-bot-master/sagiri_bot.py", line 31, in <module>
    from SAGIRIBOT.process.group_message_process import group_message_process
  File "e:\robot\sagiri-bot-master\SAGIRIBOT\process\group_message_process.py", line 144
    if achievement_list := await chat_achievement_check(group_id, sender):
                         ^
SyntaxError: invalid syntax

**Comment by SAGIRI-kawaii** [comment]
python版本？要求3.8+

**Comment by AshMOB** [comment]
好的好的我傻了orz
