### ISSUE TITLE
[Bug Report] 储存setu图片时报错

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#138]
**环境信息**

系统版本: Debian Buster x64
源码版本: commit b01d9c79f717e90cf9581723104d7b0b2ad734a3
其他信息: MySQL, Python3.8, Pillow==8.1.2, pydantic==1.7.1, graia-application-mirai==0.19.2

**问题描述**
发生了什么情况？有什么现状？是否可复现？
向群聊中发送 `添加setu图片` / `添加setu18图片` 后控制台报错
（图还是 NSFW Furry 图，就不放了）

**日志**
```
2021-09-03 13:18:51.931 | ERROR    | SAGIRIBOT.Handler.Handlers.ImageAdderHandler:handle:57 - Traceback (most recent call last):
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/ImageAdderHandler.py", line 55, in handle
    await ImageAdderHandler.add_image(path, message.get(Image))
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/ImageAdderHandler.py", line 85, in add_image
    img = IMG.open(BytesIO(img_content))
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7ff98a2c4770>
```

**Comment by SAGIRI-kawaii** [comment]
fixed
