### ISSUE TITLE
运行py文件时发生ImportError

### ISSUE THREAD

**Issue by fj233** [SAGIRI-kawaii/sagiri-bot#14]
报错如下：
`C:\Users\Administrator\Desktop\sagiri\sagiri-bot-master>py -m sagiri_bot.py
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Administrator\Desktop\sagiri\sagiri-bot-master\sagiri_bot.py", line 31, in <module>
    from SAGIRIBOT.process.group_message_process import group_message_process
  File "C:\Users\Administrator\Desktop\sagiri\sagiri-bot-master\SAGIRIBOT\process\group_message_process.py", line 38, in <module>
    from SAGIRIBOT.data_manage.get_data.get_rank import get_total_rank
ImportError: cannot import name 'get_total_rank' from 'SAGIRIBOT.data_manage.get_data.get_rank' (C:\Users\Administrator\Desktop\sagiri\sagiri-bot-master\SAGIRIBOT\data_manage\get_data\get_rank.py)`

**Comment by SAGIRI-kawaii** [comment]
请更新至最新，或直接替换 `SAGIRIBOT\data_manage\get_data\get_rank.py` 文件，上传时没有同时更新此文件导致函数缺失

**Comment by fj233** [comment]
> 请更新至最新，或直接替换 `SAGIRIBOT\data_manage\get_data\get_rank.py` 文件，上传时没有同时更新此文件导致函数缺失

已解决，感谢回复，祝您生活愉快。
