### ISSUE TITLE
[Bug Report]python main.py出错

### ISSUE THREAD

**Issue by JonathanChuyan** [SAGIRI-kawaii/sagiri-bot#141]
**环境信息**

系统版本:windows server 2016
源码版本:v2.1.7
其他信息:

**问题描述**
发生了什么情况？有什么现状？是否可复现？
一直各种提示没有moudules,一个个安装后还是报错

**日志**
Traceback (most recent call last):
  File "D:\mirai\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\__init__.py", line 18, in <module>
    from graia.application.event.lifecycle import (  # for init lifecycle events
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\event\lifecycle.py", line 3, in <module>
    from graia.broadcast.entities.event import Dispatchable, BaseDispatcher
ImportError: cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.event' (C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\broadcast\entities\event.py)
点击文本框下面小长条可以上传文件

**Comment by SAGIRI-kawaii** [comment]
pip install -U graia-application-mirai==0.19.2

**Comment by JonathanChuyan** [comment]
不好意思 还是报错...
Traceback (most recent call last):
  File "D:\mirai\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\__init__.py",
line 37, in <module>
    from .event.messages import FriendMessage, GroupMessage, TempMessage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\event\messages
.py", line 12, in <module>
    from graia.application.message.elements.internal import Source
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\message\elemen
ts\internal.py", line 700, in <module>
    Quote.update_forward_refs(MessageChain=MessageChain)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pydantic\main.py", line 677, in
update_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pydantic\typing.py", line 233, i
n update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pydantic\typing.py", line 50, in
 evaluate_forwardref
    return type_._evaluate(globalns, localns)
TypeError: _evaluate() missing 1 required positional argument: 'recursive_guard'

**Comment by SAGIRI-kawaii** [comment]
pip install -U pydantic==1.7.1

**Comment by JonathanChuyan** [comment]
这次mysql又出错了 QAQ
Traceback (most recent call last):
  File "D:\mirai\main.py", line 13, in <module>
    from WebManager.websocket import set_log
  File "D:\mirai\WebManager\websocket.py", line 6, in <module>
    from SAGIRIBOT.utils import get_config
  File "D:\mirai\SAGIRIBOT\utils.py", line 22, in <module>
    from SAGIRIBOT.ORM.AsyncORM import orm
  File "D:\mirai\SAGIRIBOT\ORM\AsyncORM.py", line 128, in <module>
    orm = AsyncORM(DB_LINK)
  File "D:\mirai\SAGIRIBOT\ORM\AsyncORM.py", line 85, in __init__
    super().__init__(conn)
  File "D:\mirai\SAGIRIBOT\ORM\AsyncORM.py", line 35, in __init__
    self.engine = create_async_engine(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 39, in create_async_engine
    sync_engine = _create_engine(*arg, **kw)
  File "<string>", line 2, in create_engine
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\url.py", line 694, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\url.py", line 755, in _parse_rfc1738_args
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'mysql:mysql+aiomysql://root:xxxx@localhost:3306/xxxx'

**Comment by nullqwertyuiop** [comment]
mysql+aiomysql://root:xxxx@localhost:3306/xxxx

**Comment by JonathanChuyan** [comment]
requirements 装过了 还是有错误  无限套娃QAQ
Traceback (most recent call last):
  File "D:\mirai\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\__init__.py", line 14, in <module>
    import graia.application.event.mirai  # for init events
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\event\__init__.py", line 3, in <module>
    from graia.broadcast import BaseEvent
ImportError: cannot import name 'BaseEvent' from 'graia.broadcast' (C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\broadcast\__init__.py)

**Comment by SAGIRI-kawaii** [comment]
pip install -U graiax-v4-dependency

**Comment by JonathanChuyan** [comment]
现在能运行了，但是一直有这个报错在重复刷屏
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'bot_data.function_called_record' doesn't exist")
[SQL: SELECT function_called_record.id, function_called_record.`time`, function_called_record.group_id, function_called_record.member_id, function_called_record.`function`, function_called_record.result
FROM function_called_record
WHERE function_called_record.`time` >= %s]
[parameters: (datetime.date(2021, 9, 7),)]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2021-09-07 17:29:31,615][ERROR]: Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\mirai\WebManager\web_manager.py", line 90, in getStatus
    "functionCalled": len(await orm.fetchall(
  File "D:\mirai\SAGIRIBOT\ORM\AsyncORM.py", line 51, in fetchall
    return (await self.execute(sql)).fetchall()
  File "D:\mirai\SAGIRIBOT\ORM\AsyncORM.py", line 48, in execute
    raise e
  File "D:\mirai\SAGIRIBOT\ORM\AsyncORM.py", line 43, in execute
    result = await session.execute(sql, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 143, in execute
    return await greenlet_spawn(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\dialects\mysql\aiomysql.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\dialects\mysql\aiomysql.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'bot_data.function_called_record' doesn't exist")
[SQL: SELECT function_called_record.id, function_called_record.`time`, function_called_record.group_id, function_called_record.member_id, function_called_record.`function`, function_called_record.result
FROM function_called_record
WHERE function_called_record.`time` >= %s]
[parameters: (datetime.date(2021, 9, 7),)]
(Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by nullqwertyuiop** [comment]
删数据库重新运行或者自己建表（）

我用mysql这样解决的

**Comment by JonathanChuyan** [comment]
谢谢  还是有问题，而且防火墙和mah都配置好了还是时不时提示8080端口连接失败，或者mysql连接失败
Linux windows server都试了 各种毛病整麻了，我个菜鸡还是用mirai的java插件算了 QAQ

**Comment by SAGIRI-kawaii** [comment]
mah版本？
