### ISSUE TITLE
[Bug Report] 机器人无法发送图片

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#145]
**环境信息**

系统版本: Debian Buster x64
源码版本: b01d9c79f717e90cf9581723104d7b0b2ad734a3
其他信息: MCL: v1.1.0; Mirai-*: 2.6.7; MAH: 1.10.0

**问题描述**
发生了什么情况？有什么现状？是否可复现？
机器人在任何情况下都无法发送图片信息或任何包含图片的信息，尽管控制台显示已发送。
根据 [MiraiForum 今天机器人突然发不出图片了](https://mirai.mamoe.net/topic/613/%E4%BB%8A%E5%A4%A9%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%AA%81%E7%84%B6%E5%8F%91%E4%B8%8D%E5%87%BA%E5%9B%BE%E7%89%87%E4%BA%86) 帖子指示似乎是 MCL 及 Mirai 版本过低导致的，但是升级后尽管不升级 MAH，也会报无法连接的错误（日志如下）。

**日志**
```
[2021-09-14 23:42:19,396][INFO]: initializing app...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8765)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/sagiri-bot/main.py", line 71, in <module>
    core.launch()
  File "/root/sagiri-bot/SAGIRIBOT/Core/AppCore.py", line 107, in launch
    self.__app.launch_blocking()
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 1503, in initialize
    await self.authenticate()
  File "/usr/local/lib/python3.8/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 301, in authenticate
    async with self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8765 ssl:default [Connect call failed ('127.0.0.1', 8765)]
```

**Comment by SAGIRI-kawaii** [comment]
我更新了没有事诶，你可以看看mcl有什么报错

**Comment by nullqwertyuiop** [comment]
怪怪的 1.10.0的mah能用2.7.1-dev的mirai吗（）

**Comment by nullqwertyuiop** [comment]
> 怪怪的 1.10.0的mah能用2.7.1-dev的mirai吗（）

怪，我这里用 MAH==1.12.0 & mirai-*==2.7-M1 还是没办法发图片

**Comment by BoBppy** [comment]
>怪怪的 1.10.0的mah能用2.7.1-dev的mirai吗（）

应该不行吧

**Comment by nullqwertyuiop** [comment]
> >怪怪的 1.10.0的mah能用2.7.1-dev的mirai吗（）
> 
> 应该不行吧

对，但是最新的1.x可以接到2.7-M1，再往上项目就没适配了
我现在用的 1.x & 2.7-M1 还是没办法发出来图片，不清楚是被风控了还是腾讯又作妖了
用其他设备发反而可以，可能又不是被降权

**Comment by nullqwertyuiop** [comment]
commit 31851fc9a76111aa0a1df6b7cb6759735a47fdd3 可以发图片诶 有考虑做新版本的适配吗@SAGIRI-kawaii

**Comment by SAGIRI-kawaii** [comment]
啊新版本直接切换mah1.12就可以继续用诶（

**Comment by nullqwertyuiop** [comment]
好吧是我又犯了端口配置不匹配的毛病（）
