### ISSUE TITLE
[Bug Report]摸等命令以及@bot时报错

### ISSUE THREAD

**Issue by ahhhhhhhman** [SAGIRI-kawaii/sagiri-bot#167]
系统版本:centOS8
[error.txt](https://github.com/SAGIRI-kawaii/sagiri-bot/files/7699115/error.txt)

**Comment by nullqwertyuiop** [comment]
请问您使用的 mirai 版本以及 mirai-api-http 版本是？

**Comment by ahhhhhhhman** [comment]
00:47:43 [INFO] Verifying "net.mamoe:mirai-console" v2.9.0-M1
  00:47:44 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.9.0-M1
  00:47:44 [INFO] Verifying "net.mamoe:mirai-core-all" v2.9.0-M1
  00:47:45 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
2021-12-13 00:47:49 I/main: Starting mirai-console...
2021-12-13 00:47:50 I/main: Backend: version 2.9.0-M1, built on 2021-11-21 07:59:25.
2021-12-13 00:47:50 I/main: Frontend Terminal: version 2.9.0-M1, provided by Mamoe Technologies
2021-12-13 00:47:50 I/main: Welcome to visit https://mirai.mamoe.net/
2021-12-13 00:47:51 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2021-12-13 00:47:51 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v1.12.0
2021-12-13 00:47:51 I/plugin: Successfully loaded plugin mirai-console-lolicon v4.2.0
2021-12-13 00:47:53 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-12-13 00:47:53 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
是这些吗

**Comment by nullqwertyuiop** [comment]
是的，按照控制台日志来看您使用的 mirai 版本为 2.9.0-M1，请降级到 2.7.1-stable。mirai-api-http == 1.12.0 最高支援的 mirai 版本为 2.7.1

**Comment by nullqwertyuiop** [comment]
降级等操作请参考 MCL 使用文档。

**Comment by ahhhhhhhman** [comment]
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    core.launch()
  File "/root/python/SAGIRIBOT/Core/AppCore.py", line 107, in launch
    self.__app.launch_blocking()
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 1574, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 1465, in initialize
    await self.activeSession()
  File "/usr/local/lib/python3.8/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 334, in activeSession
    raise_for_return_code(data)
  File "/usr/local/lib/python3.8/site-packages/graia/application/utilles.py", line 114, in raise_for_return_code
    raise exception_code
graia.application.exceptions.AccountNotFound
然后原来能用的就用不了了诶

**Comment by nullqwertyuiop** [comment]
请检查 mirai 是否正常运行，若正常运行则检查 mirai 工作目录下 config/net.mamoe.mirai-api-http/setting.yml 中账号是否与 sagiri-bot 工作目录下 config.yaml 中账号一致。
AccountNotFound 错误一般由以上几种情况造成。

**Comment by ahhhhhhhman** [comment]
在降级之前其余的功能都正常
降级之后就出现了这种问题，没有修改任何文件
然后我在mirai 工作目录下 config/net.mamoe.mirai-api-http/setting.yml没有找到账号什么的设置

**Comment by nullqwertyuiop** [comment]
我的错，找错路径了。
应该是 mirai 工作路径下的 Console/AutoLogin.yml

**Comment by nullqwertyuiop** [comment]
注意，修改时请先杀死 mcl 进程，否则修改内容不会被保存。

**Comment by ahhhhhhhman** [comment]
好了好了问题解决了
万分感谢
