### ISSUE TITLE
求助，请问健康打卡机器人怎么使用啊

### ISSUE THREAD

**Issue by ChuJian2** [SAGIRI-kawaii/sagiri-bot#171]
请问健康打卡机器人怎么使用啊，给机器人发消息没有反应。

**Comment by SAGIRI-kawaii** [comment]
将SAGIRIBOT.Handler.Handlers.JLUEpidemicReporter中line369-373取消注释

**Comment by ChuJian2** [comment]
已经取消注释了，请问是在群里面给他发消息吗，还是私聊，是发送打卡这两个字吗，我试了好几种可能，他没有反应。

**Comment by nullqwertyuiop** [comment]
> 已经取消注释了，请问是在群里面给他发消息吗，还是私聊，是发送打卡这两个字吗，我试了好几种可能，他没有反应。

（没实际使用过，个人推测）
再取消注释第 41 行注释，私聊发送 “帮助” 查看详细使用方法

**Comment by ChuJian2** [comment]
好的，可以使用了，万分感谢。

**Comment by ChuJian2** [comment]
```
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/sagiri-bot/SAGIRIBOT/Handler/Handlers/JLUEpidemicReporterHandler.py", line 414, in run
    loop.run_until_complete(app.sendFriendMessage(self.user_data["qq"], MessageChain.create([Plain(text=datetime.datetime.now().strftime('%a, %b %d %H:%M:%S') + "\n打卡成功！")])))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/sagiri-bot/SAGIRIBOT/Handler/Handlers/JLUEpidemicReporterHandler.py", line 414, in run
    loop.run_until_complete(app.sendFriendMessage(self.user_data["qq"], MessageChain.create([Plain(text=datetime.datetime.now().strftime('%a, %b %d %H:%M:%S') + "\n打卡成功！")])))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
在使用过程中，使用定时打卡后，会报一个这样的错误，但不影响使用。
