### ISSUE TITLE
[bug]获取新番时间表的功能无法使用

### ISSUE THREAD

**Issue by mzttsaintly** [SAGIRI-kawaii/sagiri-bot#18]
使用获取bilibili7日内新番时间表的handler时发生错误：

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "main.py", line 73, in group_message_handler
    if await g_handler.handle(app, message, group, member):
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/MessageHandler.py", line 67, in handle
    await g
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BiliBiliBangumiScheduleHandler.py", line 29, in handle
    set_result(message, await self.formatted_output_bangumi(days))
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/decorators.py", line 65, in wrapper
    return await func(*args, **kwargs)
TypeError: formatted_output_bangumi() missing 2 required positional arguments: 'member' and 'days'

缺少了两个参数

**Comment by SAGIRI-kawaii** [comment]
感谢，将会在下次push中修复

**Comment by SAGIRI-kawaii** [comment]
2.0.3已更新

**Comment by mzttsaintly** [comment]
已更新至2.0.3版本，但似乎并未解决这个问题，依旧出现同样的报错：

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "main.py", line 71, in group_message_handler
    if await g_handler.handle(app, message, group, member):
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/MessageHandler.py", line 73, in handle
    await g
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BiliBiliBangumiScheduleHandler.py", line 29, in handle
    set_result(message, await self.formatted_output_bangumi(days))
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/decorators.py", line 65, in wrapper
    return await func(*args, **kwargs)
TypeError: formatted_output_bangumi() missing 2 required positional arguments: 'member' and 'days'

**Comment by SAGIRI-kawaii** [comment]
> 已更新至2.0.3版本，但似乎并未解决这个问题，依旧出现同样的报错：
> 
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/graia/broadcast/**init**.py", line 204, in Executor
> > result = await run_always_await_safely(
> > File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
> > return await callable(*args, **kwargs)
> > File "main.py", line 71, in group_message_handler
> > if await g_handler.handle(app, message, group, member):
> > File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/MessageHandler.py", line 73, in handle
> > await g
> > File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BiliBiliBangumiScheduleHandler.py", line 29, in handle
> > set_result(message, await self.formatted_output_bangumi(days))
> > File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/decorators.py", line 65, in wrapper
> > return await func(*args, **kwargs)
> > TypeError: formatted_output_bangumi() missing 2 required positional arguments: 'member' and 'days'

请再次尝试更新，昨天网络错误没有注意到
