### ISSUE TITLE
[Bug Report]搜番功能坏啦

### ISSUE THREAD

**Issue by Evyde** [SAGIRI-kawaii/sagiri-bot#182]
**环境信息**

系统版本: CentOS 7
源码版本: Latest
其他信息: Mirai最新

**问题描述**
B站小程序解析、Wolfram Alpha啥的都正常，不知道这是什么问题。

**日志**

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/Handler/Handlers/BangumiSearchHandler.py", line 36, in bangumi_search_handler
    if result := await BangumiSearchHandler.handle(app, message, group, member):
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/decorators.py", line 92, in wrapper
    return await func(*args, **kwargs)
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/decorators.py", line 116, in wrapper
    return await func(*args, **kwargs)
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/Handler/Handlers/BangumiSearchHandler.py", line 54, in handle
    await app.sendGroupMessage(group, MessageChain.create([
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/application/__init__.py", line 67, in wrapped_network_action_callable
    return await network_action_callable(self, *args, **kwargs)
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/application/__init__.py", line 644, in sendGroupMessage
    response.raise_for_status()
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://127.0.0.1:55955/sendGroupMessage')
```

**Comment by nullqwertyuiop** [comment]
群组是不是有发言频率限制？

**Comment by nullqwertyuiop** [comment]
比如一分钟限发10条之类的

**Comment by SAGIRI-kawaii** [comment]
mcl处有无报错提示

**Comment by Evyde** [comment]
![image](https://user-images.githubusercontent.com/9302540/148960062-ac451c31-5701-4000-af84-4c44b861a506.png)
MCL没有报错提示

**Comment by nullqwertyuiop** [comment]
> 群组是不是有发言频率限制？

↑看看这个，已知在有频率限制的群里超过限制时会报错

**Comment by SAGIRI-kawaii** [comment]
mirai报错写的什么（

**Comment by Evyde** [comment]
> > 群组是不是有发言频率限制？
> 
> ↑看看这个，已知在有频率限制的群里超过限制时会报错

没有，没有频率限制

**Comment by Evyde** [comment]
> mirai报错写的什么（

Mirai报错怎么看啊，反正控制台里是没有

**Comment by SAGIRI-kawaii** [comment]
> > mirai报错写的什么（
> 
> Mirai报错怎么看啊，反正控制台里是没有

就是mirai-console的报错）

**Comment by Evyde** [comment]
> > > mirai报错写的什么（
> > 
> > 
> > Mirai报错怎么看啊，反正控制台里是没有
> 
> 就是mirai-console的报错）

没有，太怪了

**Comment by nullqwertyuiop** [comment]
出现问题的频率？
一次 / 偶尔几次 / 经常 / 每次

**Comment by Evyde** [comment]
> 出现问题的频率？ 一次 / 偶尔几次 / 经常 / 每次

每次

**Comment by SAGIRI-kawaii** [comment]
我这里没有问题（
mirai肯定有报错，你去启动mirai的地方看

**Comment by SAGIRI-kawaii** [comment]
> > 出现问题的频率？ 一次 / 偶尔几次 / 经常 / 每次
> 
> 每次

所以有报错吗

**Comment by Evyde** [comment]
> > > 出现问题的频率？ 一次 / 偶尔几次 / 经常 / 每次
> > 
> > 
> > 每次
> 
> 所以有报错吗

没有，难道是Mirai看错误次数太多自动禁用了？

**Comment by SAGIRI-kawaii** [comment]
妹有报错，但应该不是sagiri-bot的问题（
