### ISSUE TITLE
关于config文件里数据库链接设置的问题

### ISSUE THREAD

**Issue by zcwang666** [SAGIRI-kawaii/sagiri-bot#19]
在启动和群里有消息发送时报错：

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: setting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\graia\broadcast\__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\graia\broadcast\utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\main.py", line 75, in init
    await AppCore.get_core_instance().bot_launch_init()
  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\SAGIRIBOT\Core\AppCore.py", line 112, in bot_launch_init
    orm.session.query(Setting).update({"active": False})
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\orm\query.py", line 3163, in update
    result = self.session.execute(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\orm\session.py", line 1653, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\util\compat.py", line 198, in raise_
    raise exception
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\engine\default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: setting
[SQL: UPDATE setting SET active=?]
[parameters: (0,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

dblink配置是sqlite:///data.db，会在文件夹下生成data.db文件但是该文件为0kb
想询问您一下该如何设置才能正确使用

**Comment by SAGIRI-kawaii** [comment]
代码版本是否为最新版

**Comment by zcwang666** [comment]
是2.0.2版的

**Comment by SAGIRI-kawaii** [comment]
回去我会测试下，如果不出意外，我将在几天后更新v2.0.3，目前可以直接下载最新源代码进行使用

**Comment by zcwang666** [comment]
非常感谢

**Comment by SAGIRI-kawaii** [comment]
2.0.3已更新
