### ISSUE TITLE
网络编译器报错问题

### ISSUE THREAD

**Issue by zcwang666** [SAGIRI-kawaii/sagiri-bot#20]
最新版本程序，网络编译器报错，在群里发

super py3:
print('Hello World!')时报错：

2021-04-19 20:33:26.106 | ERROR    | asyncio.events:_run:81 - An error has been caught in function '_run', process 'MainProcess' (34112), thread 'MainThread' (32936):
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\main.py", line 70, in <module>
    core.launch()
    │    └ <function AppCore.launch at 0x03FDFD60>
    └ <SAGIRIBOT.Core.AppCore.AppCore object at 0x00B813A0>

  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\SAGIRIBOT\Core\AppCore.py", line 98, in launch
    self.__app.launch_blocking()
    └ <SAGIRIBOT.Core.AppCore.AppCore object at 0x00B813A0>

  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\graia\application\__init__.py", line 1578, in launch_blocking
    loop.run_until_complete(self.getFetching()())
    │    │                  │    └ <function GraiaMiraiApplication.getFetching at 0x034986E8>
    │    │                  └ <graia.application.GraiaMiraiApplication object at 0x050DE1B0>
    │    └ <function BaseEventLoop.run_until_complete at 0x02A196E8>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x02A7B6E8>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x02A1A460>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x029B1BB0>
    └ <Handle <TaskWakeupMethWrapper object at 0x08961118>(<_GatheringFu...specificity")>)>

> File "C:\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x08961118>(<_GatheringFu...specificity")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x08961118>(<_GatheringFu...specificity")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x08961118>(<_GatheringFu...specificity")>)>

  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\main.py", line 59, in group_message_handler
    if result := await g_handler.handle(app, message, group, member):
                       │         │      │    │        │      └ Member(id=1298808723, name='画风奇特的日哥', permission=<MemberPerm.Administrator: 'ADMINISTRATOR'>, group=Group(id=920870447, name=...
                       │         │      │    │        └ Group(id=920870447, name='鸦巢', accountPerm=<MemberPerm.Member: 'MEMBER'>)
                       │         │      │    └ MessageChain((Source(id=278160, time=datetime.datetime(2021, 4, 19, 12, 33, 20, tzinfo=datetime.timezone.utc)), Plain(type='P...
                       │         │      └ <graia.application.GraiaMiraiApplication object at 0x050DE1B0>
                       │         └ <function GroupMessageHandler.handle at 0x052DA658>
                       └ <SAGIRIBOT.Handler.MessageHandler.GroupMessageHandler object at 0x052D0FD0>

  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\SAGIRIBOT\Handler\MessageHandler.py", line 73, in handle
    await g
          └ <_GatheringFuture finished exception=ArgumentError("Textual column expression 'compile' should be explicitly declared with te...

  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\SAGIRIBOT\Handler\Handlers\NetworkCompilerHandler.py", line 27, in handle
    if not await get_setting(group.id, "compile"):
                 │           │     └ 920870447
                 │           └ Group(id=920870447, name='鸦巢', accountPerm=<MemberPerm.Member: 'MEMBER'>)
                 └ <function get_setting at 0x05FD7220>

  File "C:\Users\Administrator\Desktop\Mirai Dice 20210115\sagiri-bot-2.0.2\SAGIRIBOT\utils.py", line 183, in get_setting
    if result := list(orm.fetchone(select(setting).where(Setting.group_id == group_id))):
                      │   │        │      │              │       │           └ 920870447
                      │   │        │      │              │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x03FA4A78>
                      │   │        │      │              └ <class 'SAGIRIBOT.ORM.Tables.Setting'>
                      │   │        │      └ 'compile'
                      │   │        └ <function select at 0x0387B3D0>
                      │   └ <function Engine.fetchone at 0x03F07A48>
                      └ <SAGIRIBOT.ORM.ORM.ORM object at 0x03E919A0>

  File "<string>", line 2, in select
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\selectable.py", line 4876, in _create
    return cls._create_future_select(*args)
           │   │                      └ ('compile',)
           │   └ <classmethod object at 0x03824A48>
           └ <class 'sqlalchemy.sql.selectable.Select'>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\selectable.py", line 4816, in _create_future_select
    self._raw_columns = [
    └ <sqlalchemy.sql.selectable.Select object at 0x03FAD760>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\selectable.py", line 4817, in <listcomp>
    coercions.expect(
    │         └ <function expect at 0x03618BF8>
    └ <module 'sqlalchemy.sql.coercions' from 'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\sqlalch...
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\coercions.py", line 175, in expect
    resolved = impl._literal_coercion(
               │    └ <function _CoerceLiterals._literal_coercion at 0x0362D0B8>
               └ <sqlalchemy.sql.coercions.ColumnsClauseImpl object at 0x0362B808>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\coercions.py", line 375, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
           │    │              │        │          └ {}
           │    │              │        └ None
           │    │              └ 'compile'
           │    └ <function ColumnsClauseImpl._text_coercion at 0x0362D970>
           └ <sqlalchemy.sql.coercions.ColumnsClauseImpl object at 0x0362B808>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\sqlalchemy\sql\coercions.py", line 808, in _text_coercion
    raise exc.ArgumentError(
          │   └ <class 'sqlalchemy.exc.ArgumentError'>
          └ <module 'sqlalchemy.exc' from 'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\sqlalchemy\\exc.py'>

sqlalchemy.exc.ArgumentError: Textual column expression 'compile' should be explicitly declared with text('compile'), or use column('compile') for more specificity

并导致整个框架卡死需要重启

**Comment by SAGIRI-kawaii** [comment]
因 #19 中数据库初始化失败而产生的错误，请等待v2.0.3或在首页直接下载代码

**Comment by SAGIRI-kawaii** [comment]
2.0.3已发布

**Comment by zcwang666** [comment]
换用了2.0.3错误依然存在，首页下载代码也是......

**Comment by SAGIRI-kawaii** [comment]
> 换用了2.0.3错误依然存在，首页下载代码也是......

请再次尝试更新，昨天网络错误没有注意到
