### ISSUE TITLE
[Bug Report]无法正常启动

### ISSUE THREAD

**Issue by PositionZer0** [SAGIRI-kawaii/sagiri-bot#221]
**问题**
无法正常启动

**如何复现**
`python main.py` 后报错

**预期行为**
正常启动

**使用环境:**

- 系统: Windows Server 2019
- MAH 版本: 2.5.0
- Ariadne 版本: 0.14.1
- Python 版本: 3.10.2
- 源码版本: 3.0.4
- 其他 Graia 库版本: graia-ariadne 0.6.10，graia-broadcast 0.16.1，graia-saya 0.0.15
- 其他 有关 库版本:

**日志/截图**
将任何有关的日志/截图放到这里（控制台输出/MAH 输出/...)
```
C:\Users\Administrator\Desktop\sagiri-bot-3.0.4>python C:\Users\Administrator\Desktop\sagiri-bot-3.0.4\main.py
2022-03-17 20:36:27.588 | INFO     | sagiri_bot.core.app_core:__init__:61 - Initializing
2022-03-17 20:36:27.673 | INFO     | sagiri_bot.core.app_core:__init__:85 - Initialize end
2022-03-17 20:36:27.681 | DEBUG    | graia.saya:require:111 - require sagiri_bot.handler.handlers.abbreviated_prediction
2022-03-17 20:36:27.729 | ERROR    | graia.ariadne.util:loguru_excepthook:52 - Exception:
Traceback (most recent call last):

> File "C:\Users\Administrator\Desktop\sagiri-bot-3.0.4\main.py", line 43, in <module>
    saya.require(f"sagiri_bot.handler.handlers.{module.split('.')[0]}")
    │    └ <function Saya.require at 0x0000028305EBA560>
    └ <graia.saya.Saya object at 0x0000028302820D60>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\graia\saya\__init__.py", line 120, in require
    channel = self.require_resolve(module)
              │    │               └ 'sagiri_bot.handler.handlers.abbreviated_prediction'
              │    └ <function Saya.require_resolve at 0x0000028305EBA440>
              └ <graia.saya.Saya object at 0x0000028302820D60>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\graia\saya\__init__.py", line 76, in require_resolve
    imported_module = importlib.import_module(module, module)
                      │         │             │       └ 'sagiri_bot.handler.handlers.abbreviated_prediction'
                      │         │             └ 'sagiri_bot.handler.handlers.abbreviated_prediction'
                      │         └ <function import_module at 0x00000283025248B0>
                      └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ 'sagiri_bot.handler.handlers.abbreviated_prediction'
           │          │           │    └ 0
           │          │           └ 'sagiri_bot.handler.handlers.abbreviated_prediction'
           │          └ <function _gcd_import at 0x00000283023E3490>
           └ <module '_frozen_importlib' (frozen)>

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "C:\Users\Administrator\Desktop\sagiri-bot-3.0.4\sagiri_bot\handler\handlers\abbreviated_prediction.py", line 32, in <module>
    Sparkle(
    └ <class 'graia.ariadne.message.parser.twilight.Sparkle'>

TypeError: Sparkle.__init__() takes 2 positional arguments but 3 were given
```

config.yaml :
```
# 必要数据及设置
bot_qq: *
host_qq: *
mirai_host: http://localhost:8080
verify_key: *
db_link: sqlite+aiosqlite:///data.db
web_manager_api: true
web_manager_auto_boot: true
proxy: proxy

# 路径相关
image_path:
  setu: setu
  setu18: setu18
  real: real
  real_highq: real_highq
  bizhi: bizhi
  sketch: sketch

# 功能相关
functions:
  tencent:
    secret_id: secret_id
    secret_key: secret_key
  saucenao_api_key: saucenao_api_key
  wolfram_alpha_key: wolfram_alpha_key
  shadiao_app_name: shadiao_app_name
  github:
    username: username
    token: token
  pica:
    username: username
    password: password
    download_cache: true
    search_cache: true
    daily_download_limit: 1
    daily_search_limit: 1
    daily_random_limit: 1
    daily_rank_limit: 1
    compress_password: i_luv_sagiri

# 日志相关
log_related:
  error_retention: 14
  common_retention: 7

# 数据相关
data_related:
  lolicon_image_cache: true
  lolicon_data_cache: true
  network_data_cache: true
  automatic_update: false
  data_retention: true

# 数据库相关
database_related:
  mysql:
    disable_pooling: false
    pool_size: 40
    max_overflow: 60
```

**Comment by SAGIRI-kawaii** [comment]
目前未更新适配 `graia-ariadne 0.6+`，可降级到 `0.5.3-pre1`
