### ISSUE TITLE
[Bug Report] Wordle 报错

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#222]
**问题**

**如何复现**
使用时随机出现报错

**预期行为**

**使用环境:**

- 系统:
- MAH 版本:
- Ariadne 版本:
- Python 版本:
- 源码版本:
- 其他 Graia 库版本:
- 其他 有关 库版本:

**日志/截图**
```
Traceback (most recent call last):

  File "/root/project-null/main.py", line 83, in <module>
    core.launch()
    │    └ <function AppCore.launch at 0x7f7c518e15e0>
    └ <sagiri_bot.core.app_core.AppCore object at 0x7f7c5ca08730>

  File "/root/project-null/sagiri_bot/core/app_core.py", line 129, in launch
    self.__app.launch_blocking()
    └ <sagiri_bot.core.app_core.AppCore object at 0x7f7c5ca08730>

  File "/usr/local/lib/python3.8/site-packages/graia/ariadne/app.py", line 1714, in launch_blocking
    self.loop.run_until_complete(self.lifecycle())
    │    │    │                  │    └ <function Ariadne.lifecycle at 0x7f7c5bd1cd30>
    │    │    │                  └ <graia.ariadne.app.Ariadne object at 0x7f7c517fc1c0>
    │    │    └ <function BaseEventLoop.run_until_complete at 0x7f7c5bf78550>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <graia.ariadne.app.Ariadne object at 0x7f7c517fc1c0>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f7c5bf784c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f7c5bf7b040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f7c5bff6ee0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f7c1a782c70>(<Future finished result=None>)>
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f7c1a782c70>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f7c1a782c70>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f7c1a782c70>(<Future finished result=None>)>
> File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(target_callable, **parameter_compile_result)
                   │                       │                  └ {'event': GroupMessage(type='GroupMessage', messageChain=MessageChain([Source(id=430185, time=datetime.datetime(2022, 3, 17, ...
                   │                       └ <function InterruptControl.leader_listener_generator.<locals>.inside_listener at 0x7f7c1bdf2ca0>
                   └ <function run_always_await_safely at 0x7f7c5c786c10>
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 39, in run_always_await_safely
    return await callable(*args, **kwargs)
                 │         │       └ {'event': GroupMessage(type='GroupMessage', messageChain=MessageChain([Source(id=430185, time=datetime.datetime(2022, 3, 17, ...
                 │         └ ()
                 └ <function InterruptControl.leader_listener_generator.<locals>.inside_listener at 0x7f7c1bdf2ca0>
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/interrupt/__init__.py", line 76, in inside_listener
    future.set_result(result)
    │      │          └ False
    │      └ <method 'set_result' of '_asyncio.Future' objects>
    └ <Future finished result=False>

asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by SAGIRI-kawaii** [comment]
神秘

**Comment by SAGIRI-kawaii** [comment]
我先假装看不见这个issue，就可以偷偷把他关掉了
