### ISSUE TITLE
[bug]有关获取bilibili新番时间表的新问题

### ISSUE THREAD

**Issue by mzttsaintly** [SAGIRI-kawaii/sagiri-bot#23]
今日使用获取新番时间的handler时出现了新的报错：

> Building prefix dict from the default dictionary ...
[2021-04-24 12:34:31,643][DEBUG]: Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
[2021-04-24 12:34:31,643][DEBUG]: Loading model from cache /tmp/jieba.cache
Loading model cost 0.604 seconds.
[2021-04-24 12:34:32,247][DEBUG]: Loading model cost 0.604 seconds.
Prefix dict has been built successfully.
[2021-04-24 12:34:32,248][DEBUG]: Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "main.py", line 71, in group_message_handler
    if await g_handler.handle(app, message, group, member):
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/MessageHandler.py", line 73, in handle
    await g
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BiliBiliBangumiScheduleHandler.py", line 29, in handle
    set_result(message, await self.formatted_output_bangumi(group, member, days))
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/decorators.py", line 65, in wrapper
    return await func(*args, **kwargs)
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BiliBiliBangumiScheduleHandler.py", line 115, in formatted_output_bangumi
    formatted_bangumi_data = await BiliBiliBangumiScheduleHandler.get_formatted_new_bangumi_json()
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BiliBiliBangumiScheduleHandler.py", line 92, in get_formatted_new_bangumi_json
    temp_bangumi_data_dict["pub_index"] = data["pub_index"]
KeyError: 'pub_index'

**Comment by SAGIRI-kawaii** [comment]
已修复，请从首页下载最新版本
