### ISSUE TITLE
[Bug] 群名太长或者可能有不支持字符就报错

### ISSUE THREAD

**Issue by ForeverOpp** [SAGIRI-kawaii/sagiri-bot#3]
大佬您好，首先感谢您的机器人。  
```python
[2021-01-13 17:20:48,504][DEBUG]: caching sha2: succeeded by fast path.
[2021-01-13 17:20:48,543][DEBUG]: caching sha2: succeeded by fast path.
127914738 : 髪国异性渴望学术互助♂(¦3[▓▓]交友���
[2021-01-13 17:20:48,560][DEBUG]: caching sha2: succeeded by fast path.
Traceback (most recent call last):
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/graia/broadcast/__init__.py", line 323, in Executor
    target_callable, **parameter_compile_result
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/graia/broadcast/utilles.py", line 20, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "sagiri_bot.py", line 199, in bot_init
    await check_group_data_init(group_list)
  File "/root/sagiri-bot-master/SAGIRIBOT/basics/check_group_data_init.py", line 24, in check_group_data_init
    await execute_sql(sql)
  File "/root/sagiri-bot-master/SAGIRIBOT/basics/aio_mysql_excute.py", line 103, in execute_sql
    res = await cursor.execute(sql)
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'groupName' at row 1")
```
群名：  
`髪国异性渴望学术互助♂(¦3[▓▓]交友🔞🚱🚷  `
![image](https://user-images.githubusercontent.com/9302540/104433484-1e49bf80-55c5-11eb-8113-e7018487a9bf.png)  
草，现在才发现，这个群名好奇怪。  
环境是`MySQL 8.0`，`CentOS 7`，`Mirai`是最新版的`2.0-RC`，使用官方安装器（`MCL`）启动，`HttpApi`是最新的。但是有一个问题，就是`graia.broadcast`和`graia.scheduler`的版本似乎低于`graia.application`所要求的版本，我使用较新版本的只有`pip`的警告，暂时来看消息接收正常。  
以及您`requirements.txt`里面没有写`graia`相关的包。

**Comment by SAGIRI-kawaii** [comment]
这个是mysql的数据格式问题，因为我的机器人没有加一些有很长名字的群所以忽略了这个问题
在sql中执行 `alter table setting change groupName groupName text;` 后重启机器人应该可以解决这个问题

**Comment by ForeverOpp** [comment]
> 这个是mysql的数据格式问题，因为我的机器人没有加一些有很长名字的群所以忽略了这个问题
> 在sql中执行 `alter table setting change groupName groupName text;` 后重启机器人应该可以解决这个问题

大佬回的好快，确实执行完命令就解决了，感谢大佬。
