### ISSUE TITLE
Linux 环境下词云无法生成

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#30]
如题，排查后确认为大小写问题，将 Handler/Handlers/GroupWordCloudGeneratorHandler.py 第88行修改为 `mask = np.array(IMG.open(f'statics/wordCloud/back.jpg'))` 后可以解决

原报错信息：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/GroupWordCloudGeneratorHandler.py", line 33, in abbreviated_prediction_handler
    if result := await GroupWordCloudGeneratorHandler.handle(app, message, group, member):
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/GroupWordCloudGeneratorHandler.py", line 47, in handle
    return await GroupWordCloudGeneratorHandler.get_review(group, member, "month", "member")
  File "/root/sagiri-bot/SAGIRIBOT/decorators.py", line 78, in wrapper
    return await func(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/GroupWordCloudGeneratorHandler.py", line 182, in get_review
    Image.fromUnsafeBytes(await GroupWordCloudGeneratorHandler.draw_word_cloud(top_n))
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/GroupWordCloudGeneratorHandler.py", line 88, in draw_word_cloud
    mask = np.array(IMG.open(f'statics/wordcloud/back.jpg'))
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'statics/wordcloud/back.jpg'
```

**Comment by SAGIRI-kawaii** [comment]
fixed
