### ISSUE TITLE
Mysql报错

### ISSUE THREAD

**Issue by lzylyd** [SAGIRI-kawaii/sagiri-bot#31]
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from SAGIRIBOT.Handler.Handlers import *
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/Handler/__init__.py", line 1, in <module>
    from .MessageHandler import GroupMessageHandler, FriendMessageHandler, TempMessageHandler
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/Handler/MessageHandler.py", line 11, in <module>
    from SAGIRIBOT.Core.AppCore import AppCore
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/Core/AppCore.py", line 16, in <module>
    from SAGIRIBOT.ORM.ORM import orm
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/ORM/ORM.py", line 116, in <module>
    orm = ORM(DB_LINK)
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/ORM/ORM.py", line 78, in __init__
    super().__init__(conn)
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/ORM/ORM.py", line 31, in __init__
    self.engine = create_engine(
  File "<string>", line 2, in create_engine
  File "PATH/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "PATH/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "PATH/.local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
Exception ignored in: <function ORM.__del__ at 0x7f684b9a6310>
Traceback (most recent call last):
  File "PATH/bot/sagiri-bot-2.0.4/SAGIRIBOT/ORM/ORM.py", line 85, in __del__
    self.session.close()
AttributeError: 'ORM' object has no attribute 'session'
```

mysql版本 :5.7
py版本: Python 3.8.5
pip版本: pip 20.0.2
aiomysql                0.0.21
SQLAlchemy              1.4.15

此外 requirements.txt 好像少了 graia-scheduler 这个依赖

**Comment by SAGIRI-kawaii** [comment]
请更新最新版本

**Comment by lzylyd** [comment]
修改init解决了
