### ISSUE TITLE
自己修改了一下插件，然后再运行就出错了

### ISSUE THREAD

**Issue by s0me-body** [SAGIRI-kawaii/sagiri-bot#32]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from WebManager.websocket import set_log
  File "C:\Users\Administrator\Desktop\New\sagiri-bot-master\sagiri-bot-master\WebManager\websocket.py", line 6, in <module>
    from SAGIRIBOT.utils import get_config
  File "C:\Users\Administrator\Desktop\New\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\utils.py", line 21, in <module>
    from SAGIRIBOT.ORM.AsyncORM import orm
  File "C:\Users\Administrator\Desktop\New\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 128, in <module>
    orm = AsyncORM(DB_LINK)
  File "C:\Users\Administrator\Desktop\New\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 85, in __init__
    super().__init__(conn)
  File "C:\Users\Administrator\Desktop\New\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 35, in __init__
    self.engine = create_async_engine(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 48, in create_async_engine
    return AsyncEngine(sync_engine)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 534, in __init__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: The asyncio extension requires an async driver to be used. The loaded 'pysqlite' is not async.

删除重新下载也不行，不知道是哪的问题

**Comment by SAGIRI-kawaii** [comment]
数据库连接配置应为 `sqlite+aiosqlite:///data.db`

**Comment by s0me-body** [comment]
> 数据库连接配置应为 `sqlite+aiosqlite:///data.db`

好了，感谢
