### ISSUE TITLE
[Help]Tuple list out of range

### ISSUE THREAD

**Issue by ForeverOpp** [SAGIRI-kawaii/sagiri-bot#4]
大佬您好，首先再次感谢您的机器人。以下是日志：  
```python
[2021-01-13 17:30:45,762][INFO]: 3419347622: [髪国异性渴望学术互助♂(¦3[▓▓]交友���(127914738] L(843684354) -> '[mirai:source:141739,1610530245]不对应该是老海神了'
接收到组髪国异性渴望学术互助♂(¦3[▓▓]交友���中来自L的消息:不对应该是老海神了
[2021-01-13 17:30:45,765][DEBUG]: caching sha2: succeeded by fast path.
Traceback (most recent call last):
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/graia/broadcast/__init__.py", line 323, in Executor
    target_callable, **parameter_compile_result
  File "/root/Fake_Search_Engine/test_venv/lib/python3.7/site-packages/graia/broadcast/utilles.py", line 20, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "sagiri_bot.py", line 235, in group_message_listener
    if await get_setting(group.id, "repeat"):
  File "/root/sagiri-bot-master/SAGIRIBOT/data_manage/get_data/get_setting.py", line 23, in get_setting
    return data[0][0]
IndexError: tuple index out of range
```
只要这个群来消息，100%出现这个问题，我和机器人私拉的群没有此问题。  
环境是`MySQL 8.0`，`CentOS 7`，`Mirai`是最新版的`2.0-RC`，使用官方安装器（`MCL`）启动，`HttpApi`是最新的。

**Comment by SAGIRI-kawaii** [comment]
在执行了 #3 中的方法后这个问题应该不会再出现，这是因为群设置初始化失败导致的

**Comment by ForeverOpp** [comment]
> 在执行了 #3 中的方法后这个问题应该不会再出现，这是因为群设置初始化失败导致的

确实执行完那条SQL指令之后问题就不再出现，谢谢大佬。
