### ISSUE TITLE
[Bug Report] <Pica功能报错>

### ISSUE THREAD

**Issue by Speechless22** [SAGIRI-kawaii/sagiri-bot#404]
### 问题

使用pica random后无响应，报错

### 如何复现

arm64云主机环境

### 使用环境

```markdown
- 系统: Ubuntu 22.04.1 LTS
- mirai 版本: 2.14.0
- mirai-api-http 版本: 2.8.0
- Python 版本: 3.10.6
- 源码版本: 最新
- 其他 Graia 库版本:
- 其他 有关 库版本:
```

### 日志/截图

modules.self_contained.pica True
2023-02-15 07:26:05.781 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

  File "/home/ubuntu/Production/sagiri-bot/main.py", line 113, in <module>
    core.launch()
    │    └ <staticmethod(<function Sagiri.launch at 0xffff94dc4160>)>
    └ <core.Sagiri object at 0xffff94db28c0>

  File "/home/ubuntu/Production/sagiri-bot/core/__init__.py", line 330, in launch
    Ariadne.launch_blocking()
    │       └ <classmethod(<function Ariadne.launch_blocking at 0xffff94ffbd90>)>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/app.py", line 313, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0xffff95008a90>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0xffff94db3e80>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0xffff95f0f880>
    │   └ <launart.manager.Launart object at 0xffff94ddc0a0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/launart/manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVw...
    │    └ <function BaseEventLoop.run_until_complete at 0xffff96447760>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0xffff964476d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0xffff96451240>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0xffff963a8ca0>
    └ <Handle Task.task_wakeup(<Future finis...sg': '无效参数'})>)>
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...sg': '无效参数'})>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...sg': '无效参数'})>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...sg': '无效参数'})>)>
> File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0xffff94db3c40>, 'group': Group(id=431157584, name='No.1 Production、ΦωΦ', accoun...
                   │                └ <function pica_search at 0xffff8f048670>
                   └ <function run_always_await at 0xffff95f4acb0>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object pica_search at 0xffff8060a180>

  File "/home/ubuntu/Production/sagiri-bot/modules/self_contained/pica/__init__.py", line 245, in pica_search
    await app.send_group_message(
          │   └ <function Ariadne.send_group_message at 0xffff94e17010>
          └ <graia.ariadne.app.Ariadne object at 0xffff94db3c40>

  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/app.py", line 1721, in send_group_message
    await self.send_message(
          │    └ <function Ariadne.send_message at 0xffff94e17250>
          └ <graia.ariadne.app.Ariadne object at 0xffff94db3c40>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/app.py", line 1976, in send_message
    return await action.exception(e)
                 │      └ <staticmethod(<function SendMessageAction.exception at 0xffff95cd6320>)>
                 └ <class 'graia.ariadne.util.send.Strict'>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/typing.py", line 111, in exception
    raise item
          └ InvalidArgument('操作参数不合法, 请报告问题.', {'code': 400, 'msg': '无效参数'})
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/app.py", line 1959, in send_message
    val = await self.send_group_message(**data, action=None)
                │    │                    └ {'message': MessageChain([Forward(nodeList=[{'senderId': 1218216109, 'time': datetime.datetime(2023, 2, 15, 7, 25, 56, 303172...
                │    └ <function Ariadne.send_group_message at 0xffff94e17010>
                └ <graia.ariadne.app.Ariadne object at 0xffff94db3c40>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/app.py", line 1740, in send_group_message
    result = await self.connection.call(
                   │    │          └ <function ConnectionInterface.call at 0xffff94ffaef0>
                   │    └ <graia.ariadne.connection.ConnectionInterface object at 0xffff94ddc190>
                   └ <graia.ariadne.app.Ariadne object at 0xffff94db3c40>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/connection/__init__.py", line 182, in call
    return await connection.call(command, method, params, in_session=in_session)
                 │          │    │        │       │                  └ True
                 │          │    │        │       └ {'target': 431157584, 'messageChain': [{'type': 'Forward', 'nodeList': [{'senderId': 1218216109, 'time': datetime.datetime(20...
                 │          │    │        └ <CallMethod.POST: 'POST'>
                 │          │    └ 'sendGroupMessage'
                 │          └ <function WebsocketConnectionMixin.call at 0xffff94ffa7a0>
                 └ <WebsocketClientConnection <ConnectionStatus connected=True alive=True verified=True stage=blocking> with 2 callbacks>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sagiri-bot-AVwYQ3_2-py3.10/lib/python3.10/site-packages/graia/ariadne/connection/ws.py", line 117, in call
    return await fut
                 └ <Future finished exception=InvalidArgument('操作参数不合法, 请报告问题.', {'code': 400, 'msg': '无效 参数'})>

graia.ariadne.exception.InvalidArgument: ('操作参数不合法, 请报告问题.', {'code': 400, 'msg': '无效参数'})

**Comment by SAGIRI-kawaii** [comment]
目前 `Ariadne` 的转发消息暂未支持 `mirai-api-http 2.8.0`，因为有 break change，请先降级mah
