### ISSUE TITLE
删除回复关键词时报错 IndexError: tuple index out of range

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#41]
如题，报错内容如下。
```
2021-05-28 14:01:40.509 | INFO     | __main__:group_message_handler:52 - 收到来自群 <groupName> 中成员 <memberName> 的消息：删除回复关键词#keyword
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/KeywordReplyHandler.py", line 36, in abbreviated_prediction_handler
    if result := await KeywordReplyHandler.handle(app, message, group, member):
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/KeywordReplyHandler.py", line 56, in handle
    return await KeywordReplyHandler.delete_keyword(app, message_serialization, group, member)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/KeywordReplyHandler.py", line 142, in delete_keyword
    content_type = result[1]
IndexError: tuple index out of range
```

使用的数据库为 MySQL

**Comment by SAGIRI-kawaii** [comment]
fixed
