### ISSUE TITLE
在解析bilibili小程序时报错

### ISSUE THREAD

**Issue by mzttsaintly** [SAGIRI-kawaii/sagiri-bot#49]
解析bilibili小程序的时候报错：
> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BilibiliAppParserHandler.py", line 25, in abbreviated_prediction_handler
    if result := await BilibiliAppParserHandler.handle(app, message, group, member):
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BilibiliAppParserHandler.py", line 53, in handle
    return MessageItem(await BilibiliAppParserHandler.generate_messagechain(result), Normal(GroupStrategy()))
  File "/home/aqiang/project/mcl-1.0.4/sagiri-bot/SAGIRIBOT/Handler/Handlers/BilibiliAppParserHandler.py", line 102, in generate_messagechain
    chain_list.append(Plain(text=f"\n【分区】{bilibili_partition_dict[str(data['tid'])]['name']}->{data['tname']}\n"))
KeyError: '228'

**Comment by SAGIRI-kawaii** [comment]
有无视频链接，看起来应该是存储的分区数据不全导致的

**Comment by mzttsaintly** [comment]
视频链接：

> https://www.bilibili.com/video/BV1By4y1u7dX

**Comment by SAGIRI-kawaii** [comment]
fixed
