### ISSUE TITLE
升级 mirai-api-http 后无法正常启动 Sagiri-Bot

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#58]
报错如下，或许是 2.x 版本的 MAH 将 `authKey` 改为了 `verifyKey` 的缘故。（[迁移文档](https://github.com/project-mirai/mirai-api-http/blob/v2.0-RC1/docs/misc/Migration2.md#%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B)）
```
Traceback (most recent call last):
  File "/root/sagiri-bot/main.py", line 101, in <module>
    core.launch()
  File "/root/sagiri-bot/SAGIRIBOT/Core/AppCore.py", line 98, in launch
    self.__app.launch_blocking()
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 1574, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 1464, in initialize
    await self.authenticate()
  File "/usr/local/lib/python3.8/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/graia/application/__init__.py", line 301, in authenticate
    async with self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8765 ssl:default [Connect call failed ('127.0.0.1', 8765)]
```

**Comment by SAGIRI-kawaii** [comment]
请自行降级mirai至2.6.5，为mah问题
