### ISSUE TITLE
使用网络编译器时报错 IndexError: list index out of range

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#64]
发送的指令为：
```
super py3
print("test")
```

报错内容为：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/NetworkCompilerHandler.py", line 26, in abbreviated_prediction_handler
    if result := await NetworkCompilerHandler.handle(app, message, group, member):
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/NetworkCompilerHandler.py", line 42, in handle
    language = re.findall(r"super (.*?):", message_text, re.S)[0]
IndexError: list index out of range
```

**Comment by nullqwertyuiop** [comment]
好像我开了太多 issue 了.jpg

**Comment by SAGIRI-kawaii** [comment]
fixed
