### ISSUE TITLE
命令问题

### ISSUE THREAD

**Issue by Air433up** [SAGIRI-kawaii/sagiri-bot#70]
对管理命令setting -set setu=True real=True bizhi=True这类的无反应

**Comment by SAGIRI-kawaii** [comment]
是最新版本吗

**Comment by Air433up** [comment]
> 是最新版本吗

是的

**Comment by SAGIRI-kawaii** [comment]
是否有对代码进行修改

**Comment by Air433up** [comment]
> 是否有对代码进行修改

未曾进行修改

**Comment by SAGIRI-kawaii** [comment]
log有吗

**Comment by Air433up** [comment]
2021-07-11 10:48:19.743 | INFO     | SAGIRIBOT.Core.AppCore:__init__:44 - Initializing
2021-07-11 10:48:19.807 | INFO     | SAGIRIBOT.Core.AppCore:__init__:64 - Initialize end
2021-07-11 10:48:19.817 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.AbbreviatedPredictionHandler
2021-07-11 10:48:19.832 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.AbstractMessageTransformHandler
2021-07-11 10:48:20.573 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.AvatarFunPicHandler
2021-07-11 10:48:20.579 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BangumiInfoSearchHandler
2021-07-11 10:48:20.586 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BangumiSearchHandler
2021-07-11 10:48:20.592 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BilibiliAppParserHandler
2021-07-11 10:48:20.596 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BiliBiliBangumiScheduleHandler
2021-07-11 10:48:20.604 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.BotManagementHandler
2021-07-11 10:48:20.623 | INFO     | SAGIRIBOT.Handler.Handler:__init__:34 - Create handler -> ChatRecordHandler
2021-07-11 10:48:20.625 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ChatRecorderHandler
2021-07-11 10:48:20.631 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ChatReplyHandler
2021-07-11 10:48:20.635 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.CPGeneratorHandler
2021-07-11 10:48:20.637 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ExpressionSolverHandler
2021-07-11 10:48:21.665 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.GroupWordCloudGeneratorHandler
2021-07-11 10:48:21.671 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.HeadHandler
2021-07-11 10:48:21.679 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.HotWordsExplainerHandler
2021-07-11 10:48:21.686 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ImageAdderHandler
2021-07-11 10:48:21.698 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ImageSearchHandler
2021-07-11 10:48:21.708 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.ImageSenderHandler
2021-07-11 10:48:21.784 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.JLUCSWNoticeHandler
2021-07-11 10:48:21.792 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.JokeHandler
2021-07-11 10:48:21.797 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.KeywordReplyHandler
2021-07-11 10:48:21.803 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LatexGeneratorHandler
2021-07-11 10:48:21.809 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LeetcodeInfoHandler
2021-07-11 10:48:21.815 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LoliconKeywordSearchHandler
2021-07-11 10:48:21.819 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.LOLItemRaidersHandler
2021-07-11 10:48:21.823 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.MarketingContentGeneratorHandler
2021-07-11 10:48:21.825 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.MessageMergeHandler
2021-07-11 10:48:21.831 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.MiraiEventHandler
2021-07-11 10:48:21.836 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.NetworkCompilerHandler
2021-07-11 10:48:21.842 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PDFSearchHandler
2021-07-11 10:48:21.850 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PeroDogHandler
2021-07-11 10:48:21.858 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PhantomTankHandler
2021-07-11 10:48:21.862 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.PoisonousChickenSoupHandler
2021-07-11 10:48:21.881 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.QrCodeGeneratorHandler
2021-07-11 10:48:21.887 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.RepeaterHandler
2021-07-11 10:48:21.903 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.SpeakHandler
2021-07-11 10:48:21.911 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.StatusPresenterHandler
2021-07-11 10:48:21.917 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.SteamGameInfoSearchHandler
2021-07-11 10:48:21.920 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.StylePictureGeneraterHandler
2021-07-11 10:48:21.926 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.Tarot
2021-07-11 10:48:21.930 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.TodayInHistoryHandler
2021-07-11 10:48:21.940 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.TrendingHandlers
2021-07-11 10:48:21.950 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.WolframAlphaHandler
2021-07-11 10:48:21.958 | INFO     | graia.saya:require:95 - module loading finished: SAGIRIBOT.Handler.Handlers.__init__
2021-07-11 10:48:22.046 | INFO     | SAGIRIBOT.Core.AppCore:config_check:156 - checking config
2021-07-11 10:48:38.857 | INFO     | __main__:group_message_handler:53 - 收到来自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set speak_mode=chat
2021-07-11 10:48:42.476 | INFO     | __main__:group_message_handler:53 - 收到来自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set setu=True
2021-07-11 10:49:02.163 | INFO     | __main__:group_message_handler:53 - 收到来自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set setu=True
2021-07-11 10:49:02.370 | SUCCESS  | SAGIRIBOT.MessageSender.MessageSender:send:54 - 成功向群 <口袋48> 发送消息 - setting –set setu=True
2021-07-11 10:49:15.445 | INFO     | __main__:group_message_handler:53 - 收到来自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：我的月内总结
2021-07-11 10:49:24.028 | INFO     | __main__:group_message_handler:53 - 收到来自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set speak_mode=chat

**Comment by Air433up** [comment]
控制台输出内容如下
2021-07-11 10:48:19.832 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.AbstractMessageTransformHandler
2021-07-11 10:48:19.834 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.AvatarFunPicHandler
2021-07-11 10:48:20.573 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.AvatarFunPicHandler
2021-07-11 10:48:20.575 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.BangumiInfoSearchHandler
2021-07-11 10:48:20.579 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.BangumiInfoSearchHandler
2021-07-11 10:48:20.580 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.BangumiSearchHandler
2021-07-11 10:48:20.586 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.BangumiSearchHandler
2021-07-11 10:48:20.588 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.BilibiliAppParserHandler
2021-07-11 10:48:20.592 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.BilibiliAppParserHandler
2021-07-11 10:48:20.594 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.BiliBiliBangumiScheduleHandler
2021-07-11 10:48:20.596 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.BiliBiliBangumiScheduleHandler
2021-07-11 10:48:20.600 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.BotManagementHandler
2021-07-11 10:48:20.604 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.BotManagementHandler
2021-07-11 10:48:20.608 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.ChatRecorderHandler
2021-07-11 10:48:20.623 | INFO     | SAGIRIBOT.Handler.Handler:__init__:34 - Cre
ate handler -> ChatRecordHandler
2021-07-11 10:48:20.625 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.ChatRecorderHandler
2021-07-11 10:48:20.629 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.ChatReplyHandler
2021-07-11 10:48:20.631 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.ChatReplyHandler
2021-07-11 10:48:20.633 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.CPGeneratorHandler
2021-07-11 10:48:20.635 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.CPGeneratorHandler
2021-07-11 10:48:20.637 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.ExpressionSolverHandler
2021-07-11 10:48:20.637 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.ExpressionSolverHandler
2021-07-11 10:48:20.639 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.GroupWordCloudGeneratorHandler
2021-07-11 10:48:21.665 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.GroupWordCloudGeneratorHandler
2021-07-11 10:48:21.669 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.HeadHandler
2021-07-11 10:48:21.671 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.HeadHandler
2021-07-11 10:48:21.675 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.HotWordsExplainerHandler
2021-07-11 10:48:21.679 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.HotWordsExplainerHandler
2021-07-11 10:48:21.680 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.ImageAdderHandler
2021-07-11 10:48:21.686 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.ImageAdderHandler
2021-07-11 10:48:21.688 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.ImageSearchHandler
2021-07-11 10:48:21.698 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.ImageSearchHandler
2021-07-11 10:48:21.702 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.ImageSenderHandler
2021-07-11 10:48:21.708 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.ImageSenderHandler
2021-07-11 10:48:21.710 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.JLUCSWNoticeHandler
2021-07-11 10:48:21.784 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.JLUCSWNoticeHandler
2021-07-11 10:48:21.788 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.JokeHandler
2021-07-11 10:48:21.792 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.JokeHandler
2021-07-11 10:48:21.793 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.KeywordReplyHandler
2021-07-11 10:48:21.797 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.KeywordReplyHandler
2021-07-11 10:48:21.799 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.LatexGeneratorHandler
2021-07-11 10:48:21.803 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.LatexGeneratorHandler
2021-07-11 10:48:21.805 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.LeetcodeInfoHandler
2021-07-11 10:48:21.809 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.LeetcodeInfoHandler
2021-07-11 10:48:21.811 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.LoliconKeywordSearchHandler
2021-07-11 10:48:21.815 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.LoliconKeywordSearchHandler
2021-07-11 10:48:21.817 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.LOLItemRaidersHandler
2021-07-11 10:48:21.819 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.LOLItemRaidersHandler
2021-07-11 10:48:21.821 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.MarketingContentGeneratorHandler
2021-07-11 10:48:21.823 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.MarketingContentGeneratorHandler
2021-07-11 10:48:21.825 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.MessageMergeHandler
2021-07-11 10:48:21.825 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.MessageMergeHandler
2021-07-11 10:48:21.827 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.MiraiEventHandler
2021-07-11 10:48:21.831 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.MiraiEventHandler
2021-07-11 10:48:21.834 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.NetworkCompilerHandler
2021-07-11 10:48:21.836 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.NetworkCompilerHandler
2021-07-11 10:48:21.840 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.PDFSearchHandler
2021-07-11 10:48:21.842 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.PDFSearchHandler
2021-07-11 10:48:21.846 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.PeroDogHandler
2021-07-11 10:48:21.850 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.PeroDogHandler
2021-07-11 10:48:21.854 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.PhantomTankHandler
2021-07-11 10:48:21.858 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.PhantomTankHandler
2021-07-11 10:48:21.860 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.PoisonousChickenSoupHandler
2021-07-11 10:48:21.862 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.PoisonousChickenSoupHandler
2021-07-11 10:48:21.864 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.QrCodeGeneratorHandler
2021-07-11 10:48:21.881 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.QrCodeGeneratorHandler
2021-07-11 10:48:21.883 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.RepeaterHandler
2021-07-11 10:48:21.887 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.RepeaterHandler
2021-07-11 10:48:21.891 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.SpeakHandler
2021-07-11 10:48:21.903 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.SpeakHandler
2021-07-11 10:48:21.905 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.StatusPresenterHandler
2021-07-11 10:48:21.911 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.StatusPresenterHandler
2021-07-11 10:48:21.913 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.SteamGameInfoSearchHandler
2021-07-11 10:48:21.917 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.SteamGameInfoSearchHandler
2021-07-11 10:48:21.918 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.StylePictureGeneraterHandler
2021-07-11 10:48:21.920 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.StylePictureGeneraterHandler
2021-07-11 10:48:21.924 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.Tarot
2021-07-11 10:48:21.926 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.Tarot
2021-07-11 10:48:21.928 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.TodayInHistoryHandler
2021-07-11 10:48:21.930 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.TodayInHistoryHandler
2021-07-11 10:48:21.934 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.TrendingHandlers
2021-07-11 10:48:21.940 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.TrendingHandlers
2021-07-11 10:48:21.944 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.WolframAlphaHandler
2021-07-11 10:48:21.950 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.WolframAlphaHandler
2021-07-11 10:48:21.952 | DEBUG    | graia.saya:require:76 - require SAGIRIBOT.H
andler.Handlers.__init__
2021-07-11 10:48:21.958 | INFO     | graia.saya:require:95 - module loading fini
shed: SAGIRIBOT.Handler.Handlers.__init__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\thread
ing.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\thread
ing.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\main.py", line 90, in ma
nagement_boot
    from WebManager.web_manager import run_api
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\WebManager\web_manager.p
y", line 102
    uvicorn.run(app, host="127.0.0.1" port=8000, log_level="error")
                                      ^
SyntaxError: invalid syntax
[2021-07-11 10:48:22,019][INFO]: initializing app...
[2021-07-11 10:48:22,041][INFO]: detecting remote's version...
2021-07-11 10:48:22.046 | INFO     | SAGIRIBOT.Core.AppCore:config_check:156 - c
hecking config
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\graia\broadcast\__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\graia\broadcast\utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\main.py", line 85, in in
it
    await core.bot_launch_init()
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\SAGIRIBOT\Core\AppCore.p
y", line 120, in bot_launch_init
    self.config_check()
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\SAGIRIBOT\Core\AppCore.p
y", line 163, in config_check
    if self.__config["saucenaoApiKey"] == "balabala":
KeyError: 'saucenaoApiKey'
[2021-07-11 10:48:22,058][INFO]: detected remote's version: 1.11.0
[2021-07-11 10:48:22,060][INFO]: using pure websocket to receive event
[2021-07-11 10:48:22,060][INFO]: event receive method checked.
[2021-07-11 10:48:22,062][INFO]: this application's initialization has been comp
leted.
[2021-07-11 10:48:22,062][INFO]: --- setting start ---
[2021-07-11 10:48:22,062][INFO]: broadcast using: <graia.broadcast.Broadcast obj
ect at 0x0000008E332259A0>
[2021-07-11 10:48:22,064][INFO]: enable log of chat: no
[2021-07-11 10:48:22,064][INFO]: debug: no
[2021-07-11 10:48:22,064][INFO]: version(remote): 1.11.0
[2021-07-11 10:48:22,064][INFO]: --- setting end ---
[2021-07-11 10:48:22,066][INFO]: application has been initialized, used 0.0469s
[2021-07-11 10:48:22,066][INFO]: websocket daemon: websocket connection starting
...
[2021-07-11 10:48:22,070][INFO]: websocket: connected
[2021-07-11 10:48:22,070][INFO]: websocket: ping task created
2021-07-11 10:48:38.857 | INFO     | __main__:group_message_handler:53 - 收到来
自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set speak_mode=chat
Building prefix dict from the default dictionary ...
[2021-07-11 10:48:38,989][DEBUG]: Building prefix dict from the default dictiona
ry ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\2\jieba.cache
[2021-07-11 10:48:38,991][DEBUG]: Loading model from cache C:\Users\ADMINI~1\App
Data\Local\Temp\2\jieba.cache
Loading model cost 0.960 seconds.
[2021-07-11 10:48:39,949][DEBUG]: Loading model cost 0.960 seconds.
Prefix dict has been built successfully.
[2021-07-11 10:48:39,951][DEBUG]: Prefix dict has been built successfully.
2021-07-11 10:48:42.476 | INFO     | __main__:group_message_handler:53 - 收到来
自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set setu=True
2021-07-11 10:49:02.163 | INFO     | __main__:group_message_handler:53 - 收到来
自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set setu=True
[2021-07-11 10:49:02,368][INFO]: [BOT 3376317175] Group(1085998084) <- 'setting
–set setu=True'
2021-07-11 10:49:02.370 | SUCCESS  | SAGIRIBOT.MessageSender.MessageSender:send:
54 - 成功向群 <口袋48> 发送消息 - setting –set setu=True
2021-07-11 10:49:15.445 | INFO     | __main__:group_message_handler:53 - 收到来
自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：我的月内总结
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\graia\broadcast\__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\graia\broadcast\utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\SAGIRIBOT\Handler\Handle
rs\GroupWordCloudGeneratorHandler.py", line 35, in abbreviated_prediction_handle
r
    if result := await GroupWordCloudGeneratorHandler.handle(app, message, group
, member):
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\SAGIRIBOT\Handler\Handle
rs\GroupWordCloudGeneratorHandler.py", line 49, in handle
    return await GroupWordCloudGeneratorHandler.get_review(group, member, "month
", "member")
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\SAGIRIBOT\decorators.py"
, line 65, in wrapper
    frequency_limit_instance = GlobalFrequencyLimitDict()
  File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.1\SAGIRIBOT\frequency_limi
t_module.py", line 12, in _singleton
    _instance[cls] = cls(*args, **kwargs)
TypeError: __new__() missing 1 required positional argument: 'frequency_limit_di
ct'
2021-07-11 10:49:24.028 | INFO     | __main__:group_message_handler:53 - 收到来
自群 <口袋48> 中成员 <୧⍤⃝😆> 的消息：setting –set speak_mode=chat

**Comment by SAGIRI-kawaii** [comment]
初始化需要一段时间，目前还是没有响应吗，尝试重新下载最新代码并覆盖原有文件

**Comment by Air433up** [comment]
> 初始化需要状态，当前还是没有响应吗，喉咙重新下载最新代码并覆盖原有文件

依旧如此
