### ISSUE TITLE
2.1.6启动报错

### ISSUE THREAD

**Issue by ningmengchacha** [SAGIRI-kawaii/sagiri-bot#87]
2021-07-29 19:59:21.096 | INFO     | graia.saya:require:128 - module loading finished: SAGIRIBOT.Handler.Handlers.__init__
[2021-07-29 19:59:21,287][INFO]: initializing app...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\WebManager\web_manager.py", line 90, in getStatus
    "functionCalled": len(await orm.fetchall(
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 51, in fetchall
    return (await self.execute(sql)).fetchall()
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 48, in execute
    raise e
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 43, in execute
    result = await session.execute(sql, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 143, in execute
    return await greenlet_spawn(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: function_called_record
[SQL: SELECT function_called_record.id, function_called_record.time, function_called_record.group_id, function_called_record.member_id, function_called_record.function, function_called_record.result
FROM function_called_record
WHERE function_called_record.time >= ?]
[parameters: ('2021-07-29',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2021-07-29 19:59:21,724][ERROR]: Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\WebManager\web_manager.py", line 90, in getStatus
    "functionCalled": len(await orm.fetchall(
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 51, in fetchall
    return (await self.execute(sql)).fetchall()
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 48, in execute
    raise e
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\ORM\AsyncORM.py", line 43, in execute
    result = await session.execute(sql, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 143, in execute
    return await greenlet_spawn(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: function_called_record
[SQL: SELECT function_called_record.id, function_called_record.time, function_called_record.group_id, function_called_record.member_id, function_called_record.function, function_called_record.result
FROM function_called_record
WHERE function_called_record.time >= ?]
[parameters: ('2021-07-29',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
ERROR:    Exception in ASGI application

这个怎么解决?

**Comment by SAGIRI-kawaii** [comment]
是否有更改alembic.ini

**Comment by ningmengchacha** [comment]
> 是否有更改alembic.ini

alembic.ini:       sqlalchemy.url = sqlite:///data.db
config.yaml:      DBLink: sqlite+aiosqlite:///data.db

应该怎么改?

**Comment by ningmengchacha** [comment]
> 是否有更改alembic.ini

我发现我的mirai-api-http好像有点问题 , 怎么都连不上 , 不知道是不是因为这个问题 :raised_eyebrow:

**Comment by SAGIRI-kawaii** [comment]
尝试关闭webManager
将 `config.yaml` 中 webManagerApi 与 webManagerAutoBoot 都设为false再重新启动是否会出现错误

**Comment by ningmengchacha** [comment]
> 尝试关闭webManager
> 将 `config.yaml` 中 webManagerApi 与 webManagerAutoBoot 都设为false再重新启动是否会出现错误

关掉这两个就好了 , 但是为啥呢

**Comment by ningmengchacha** [comment]
顺便问一下这是怎么回事 ? 
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:2233 ssl:default [远程计算机拒绝网络连接。]

**Comment by SAGIRI-kawaii** [comment]
可能是FastApi的问题，我没有遇到过这个问题

**Comment by SAGIRI-kawaii** [comment]
> 顺便问一下这是怎么回事 ?
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:2233 ssl:default [远程计算机拒绝网络连接。]

有可能是mah与mirai版本不匹配的问题，尝试升级mah至最新1.x或降级mirai

**Comment by ningmengchacha** [comment]
> > 顺便问一下这是怎么回事 ?
> > aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:2233 ssl:default [远程计算机拒绝网络连接。]
> 
> 有可能是mah与mirai版本不匹配的问题，尝试升级mah至最新1.x或降级mirai

好的感谢
