### ISSUE TITLE
AttributeError: 'Element' object has no attribute 'asDisplay'

### ISSUE THREAD

**Issue by ningmengchacha** [SAGIRI-kawaii/sagiri-bot#88]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\graia\broadcast\__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\graia\broadcast\utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\Handler\Handlers\BotManagementHandler.py", line 20, in abbreviated_prediction_handler
    if result := await BotManagementHandler.handle(app, message, group, member):
  File "C:\Users\Administrator\OneDrive\应用\mirai\sagiri-bot-master\sagiri-bot-master\SAGIRIBOT\Handler\Handlers\BotManagementHandler.py", line 31, in handle
    message_text = message.asDisplay()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\graia\application\message\chain.py", line 285, in asDisplay
    return "".join(i.asDisplay() for i in self.__root__)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\graia\application\message\chain.py", line 285, in <genexpr>
    return "".join(i.asDisplay() for i in self.__root__)
AttributeError: 'Element' object has no attribute 'asDisplay'

发送任意消息就会出现 一大窜这样的消息 , 这是mirai版本的问题吗 ?

**Comment by ningmengchacha** [comment]
Python 3.8.8

**Comment by SAGIRI-kawaii** [comment]
pip install -U graia-application-mirai==0.19.2

**Comment by ningmengchacha** [comment]
> pip install -U graia-application-mirai==0.19.2

还是不行 , 一样的错误

**Comment by SAGIRI-kawaii** [comment]
pip install -U pydantic==1.7.1

**Comment by ningmengchacha** [comment]
感谢:zany_face:
