### ISSUE TITLE
switch 为 False 时接收消息报错

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#91]
报错内容如下，因为输出太长所以截了一部分，其余与如下所示的除 handler 名外基本相同，
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 222, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/TodayInHistoryHandler.py", line 24, in today_in_history_handler
    if result := await TodayInHistoryHandler.handle(app, message, group, member):
  File "/root/sagiri-bot/SAGIRIBOT/decorators.py", line 88, in wrapper
    if not await user_permission_require(group_id, member_id, 2):
  File "/root/sagiri-bot/SAGIRIBOT/utils.py", line 204, in user_permission_require
    await orm.insert_or_ignore(UserPermission, {"group_id": group, "member_id": member, "level": 1})
TypeError: insert_or_ignore() missing 1 required positional argument: 'dt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 222, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/ChatReplyHandler.py", line 36, in chat_reply_handler
    if result := await ChatReplyHandler.handle(app, message, group, member):
  File "/root/sagiri-bot/SAGIRIBOT/decorators.py", line 88, in wrapper
    if not await user_permission_require(group_id, member_id, 2):
  File "/root/sagiri-bot/SAGIRIBOT/utils.py", line 204, in user_permission_require
    await orm.insert_or_ignore(UserPermission, {"group_id": group, "member_id": member, "level": 1})
TypeError: insert_or_ignore() missing 1 required positional argument: 'dt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 222, in Executor
    result = await run_always_await_safely(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/sagiri-bot/SAGIRIBOT/Handler/Handlers/BotManagementHandler.py", line 21, in abbreviated_prediction_handler
    if result := await BotManagementHandler.handle(app, message, group, member):
  File "/root/sagiri-bot/SAGIRIBOT/decorators.py", line 88, in wrapper
    if not await user_permission_require(group_id, member_id, 2):
  File "/root/sagiri-bot/SAGIRIBOT/utils.py", line 204, in user_permission_require
    await orm.insert_or_ignore(UserPermission, {"group_id": group, "member_id": member, "level": 1})
TypeError: insert_or_ignore() missing 1 required positional argument: 'dt'
```

**Comment by SAGIRI-kawaii** [comment]
fixed
